spring.application.name=api-gateway
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/microservices

management.endpoint.gateway.access=read-only
management.endpoints.web.exposure.include=health,info,gateway
