apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  PRODUCT_SERVICE_URL: http://product-service:8081
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: product_db